// Complete Database of the 118 Elements of the Periodic Table
// Categories used:
// - alkali-metal
// - alkaline-earth-metal
// - transition-metal
// - post-transition-metal
// - metalloid
// - reactive-nonmetal
// - noble-gas
// - lanthanide
// - actinide

export const elements = [
  {
    number: 1,
    symbol: "H",
    name: "Hydrogen",
    mass: 1.008,
    category: "reactive-nonmetal",
    shells: [1],
    period: 1,
    group: 1,
    meltingPoint: 14.01,
    boilingPoint: 20.28,
    density: 0.00008988,
    electronegativity: 2.2,
    stateAtSTP: "gas",
    discoverer: "Henry Cavendish",
    discoveryYear: 1766,
    summary: "The most abundant chemical substance in the Universe, making up about 75% of all normal matter.",
    shellConfig: "1s¹"
  },
  {
    number: 2,
    symbol: "He",
    name: "Helium",
    mass: 4.0026,
    category: "noble-gas",
    shells: [2],
    period: 1,
    group: 18,
    meltingPoint: 0.95,
    boilingPoint: 4.22,
    density: 0.0001785,
    electronegativity: null,
    stateAtSTP: "gas",
    discoverer: "Jansen & Lockyer",
    discoveryYear: 1868,
    summary: "A colorless, odorless, tasteless, non-toxic, and inert gas that heads the noble gas series.",
    shellConfig: "1s²"
  },
  {
    number: 3,
    symbol: "Li",
    name: "Lithium",
    mass: 6.94,
    category: "alkali-metal",
    shells: [2, 1],
    period: 2,
    group: 1,
    meltingPoint: 453.69,
    boilingPoint: 1615,
    density: 0.534,
    electronegativity: 0.98,
    stateAtSTP: "solid",
    discoverer: "Johan August Arfwedson",
    discoveryYear: 1817,
    summary: "The lightest metal and the least dense solid element under standard conditions.",
    shellConfig: "[He] 2s¹"
  },
  {
    number: 4,
    symbol: "Be",
    name: "Beryllium",
    mass: 9.0122,
    category: "alkaline-earth-metal",
    shells: [2, 2],
    period: 2,
    group: 2,
    meltingPoint: 1560,
    boilingPoint: 2742,
    density: 1.85,
    electronegativity: 1.57,
    stateAtSTP: "solid",
    discoverer: "Louis Nicolas Vauquelin",
    discoveryYear: 1797,
    summary: "A relatively rare metal in the universe, often forming into crystals when blended with emeralds.",
    shellConfig: "[He] 2s²"
  },
  {
    number: 5,
    symbol: "B",
    name: "Boron",
    mass: 10.81,
    category: "metalloid",
    shells: [2, 3],
    period: 2,
    group: 13,
    meltingPoint: 2349,
    boilingPoint: 4200,
    density: 2.08,
    electronegativity: 2.04,
    stateAtSTP: "solid",
    discoverer: "Joseph Louis Gay-Lussac",
    discoveryYear: 1808,
    summary: "A low-abundance element in the Solar System, commonly used in fiberglass and ceramics.",
    shellConfig: "[He] 2s² 2p¹"
  },
  {
    number: 6,
    symbol: "C",
    name: "Carbon",
    mass: 12.011,
    category: "reactive-nonmetal",
    shells: [2, 4],
    period: 2,
    group: 14,
    meltingPoint: 3823,
    boilingPoint: 4300,
    density: 2.267,
    electronegativity: 2.55,
    stateAtSTP: "solid",
    discoverer: "Ancient Egypt",
    discoveryYear: "Unknown",
    summary: "The chemical basis for all known organic life, highly versatile in forming chemical bonds.",
    shellConfig: "[He] 2s² 2p²"
  },
  {
    number: 7,
    symbol: "N",
    name: "Nitrogen",
    mass: 14.007,
    category: "reactive-nonmetal",
    shells: [2, 5],
    period: 2,
    group: 15,
    meltingPoint: 63.15,
    boilingPoint: 77.36,
    density: 0.0012506,
    electronegativity: 3.04,
    stateAtSTP: "gas",
    discoverer: "Daniel Rutherford",
    discoveryYear: 1772,
    summary: "Makes up about 78% of Earth's atmosphere, essential for fertilizers and amino acids.",
    shellConfig: "[He] 2s² 2p³"
  },
  {
    number: 8,
    symbol: "O",
    name: "Oxygen",
    mass: 15.999,
    category: "reactive-nonmetal",
    shells: [2, 6],
    period: 2,
    group: 16,
    meltingPoint: 54.36,
    boilingPoint: 90.2,
    density: 0.001429,
    electronegativity: 3.44,
    stateAtSTP: "gas",
    discoverer: "Carl Wilhelm Scheele",
    discoveryYear: 1771,
    summary: "Highly reactive nonmetal that forms oxides with most elements, driving aerobic respiration.",
    shellConfig: "[He] 2s² 2p⁴"
  },
  {
    number: 9,
    symbol: "F",
    name: "Fluorine",
    mass: 18.998,
    category: "reactive-nonmetal",
    shells: [2, 7],
    period: 2,
    group: 17,
    meltingPoint: 53.48,
    boilingPoint: 85.03,
    density: 0.001696,
    electronegativity: 3.98,
    stateAtSTP: "gas",
    discoverer: "André-Marie Ampère",
    discoveryYear: 1810,
    summary: "The most electronegative and reactive of all elements, extremely toxic in elemental form.",
    shellConfig: "[He] 2s² 2p⁵"
  },
  {
    number: 10,
    symbol: "Ne",
    name: "Neon",
    mass: 20.18,
    category: "noble-gas",
    shells: [2, 8],
    period: 2,
    group: 18,
    meltingPoint: 24.56,
    boilingPoint: 27.07,
    density: 0.0009002,
    electronegativity: null,
    stateAtSTP: "gas",
    discoverer: "Ramsay & Travers",
    discoveryYear: 1898,
    summary: "Glows with a reddish-orange light when used in high-voltage glow discharge lamps.",
    shellConfig: "[He] 2s² 2p⁶"
  },
  {
    number: 11,
    symbol: "Na",
    name: "Sodium",
    mass: 22.99,
    category: "alkali-metal",
    shells: [2, 8, 1],
    period: 3,
    group: 1,
    meltingPoint: 370.87,
    boilingPoint: 1156,
    density: 0.968,
    electronegativity: 0.93,
    stateAtSTP: "solid",
    discoverer: "Humphry Davy",
    discoveryYear: 1807,
    summary: "A soft, silvery-white, highly reactive alkali metal that is an essential electrolyte for life.",
    shellConfig: "[Ne] 3s¹"
  },
  {
    number: 12,
    symbol: "Mg",
    name: "Magnesium",
    mass: 24.305,
    category: "alkaline-earth-metal",
    shells: [2, 8, 2],
    period: 3,
    group: 2,
    meltingPoint: 923,
    boilingPoint: 1363,
    density: 1.738,
    electronegativity: 1.31,
    stateAtSTP: "solid",
    discoverer: "Joseph Black",
    discoveryYear: 1755,
    summary: "A shiny gray solid metal which burns with a brilliant white light when ignited in air.",
    shellConfig: "[Ne] 3s²"
  },
  {
    number: 13,
    symbol: "Al",
    name: "Aluminum",
    mass: 26.982,
    category: "post-transition-metal",
    shells: [2, 8, 3],
    period: 3,
    group: 13,
    meltingPoint: 933.47,
    boilingPoint: 2792,
    density: 2.7,
    electronegativity: 1.61,
    stateAtSTP: "solid",
    discoverer: "Hans Christian Ørsted",
    discoveryYear: 1824,
    summary: "Lightweight, non-magnetic, and ductile metal widely used in aerospace and packaging.",
    shellConfig: "[Ne] 3s² 3p¹"
  },
  {
    number: 14,
    symbol: "Si",
    name: "Silicon",
    mass: 28.085,
    category: "metalloid",
    shells: [2, 8, 4],
    period: 3,
    group: 14,
    meltingPoint: 1687,
    boilingPoint: 3538,
    density: 2.329,
    electronegativity: 1.9,
    stateAtSTP: "solid",
    discoverer: "Jöns Jacob Berzelius",
    discoveryYear: 1823,
    summary: "A hard, crystalline metalloid that is the foundation of modern semiconductor electronics.",
    shellConfig: "[Ne] 3s² 3p²"
  },
  {
    number: 15,
    symbol: "P",
    name: "Phosphorus",
    mass: 30.974,
    category: "reactive-nonmetal",
    shells: [2, 8, 5],
    period: 3,
    group: 15,
    meltingPoint: 317.3,
    boilingPoint: 553.6,
    density: 1.823,
    electronegativity: 2.19,
    stateAtSTP: "solid",
    discoverer: "Hennig Brand",
    discoveryYear: 1669,
    summary: "Exists in red or white forms, essential for DNA structures and energy transfer in ATP.",
    shellConfig: "[Ne] 3s² 3p³"
  },
  {
    number: 16,
    symbol: "S",
    name: "Sulfur",
    mass: 32.06,
    category: "reactive-nonmetal",
    shells: [2, 8, 6],
    period: 3,
    group: 16,
    meltingPoint: 388.36,
    boilingPoint: 717.8,
    density: 2.07,
    electronegativity: 2.58,
    stateAtSTP: "solid",
    discoverer: "Ancient China",
    discoveryYear: "Before 2000 BCE",
    summary: "Bright yellow crystalline solid, historically known as brimstone, smelling of volcanic gases.",
    shellConfig: "[Ne] 3s² 3p⁴"
  },
  {
    number: 17,
    symbol: "Cl",
    name: "Chlorine",
    mass: 35.45,
    category: "reactive-nonmetal",
    shells: [2, 8, 7],
    period: 3,
    group: 17,
    meltingPoint: 171.6,
    boilingPoint: 239.11,
    density: 0.0032,
    electronegativity: 3.16,
    stateAtSTP: "gas",
    discoverer: "Carl Wilhelm Scheele",
    discoveryYear: 1774,
    summary: "A pale yellow-green gas that is a highly effective disinfectant and common salt component.",
    shellConfig: "[Ne] 3s² 3p⁵"
  },
  {
    number: 18,
    symbol: "Ar",
    name: "Argon",
    mass: 39.948,
    category: "noble-gas",
    shells: [2, 8, 8],
    period: 3,
    group: 18,
    meltingPoint: 83.8,
    boilingPoint: 87.3,
    density: 0.001784,
    electronegativity: null,
    stateAtSTP: "gas",
    discoverer: "Rayleigh & Ramsay",
    discoveryYear: 1894,
    summary: "The third-most abundant gas in the Earth's atmosphere, frequently used as an inert shield in welding.",
    shellConfig: "[Ne] 3s² 3p⁶"
  },
  {
    number: 19,
    symbol: "K",
    name: "Potassium",
    mass: 39.098,
    category: "alkali-metal",
    shells: [2, 8, 8, 1],
    period: 4,
    group: 1,
    meltingPoint: 336.5,
    boilingPoint: 1032,
    density: 0.89,
    electronegativity: 0.82,
    stateAtSTP: "solid",
    discoverer: "Humphry Davy",
    discoveryYear: 1807,
    summary: "Silvery-white metal that reacts violently with water. Crucial for neuron functioning.",
    shellConfig: "[Ar] 4s¹"
  },
  {
    number: 20,
    symbol: "Ca",
    name: "Calcium",
    mass: 40.078,
    category: "alkaline-earth-metal",
    shells: [2, 8, 8, 2],
    period: 4,
    group: 2,
    meltingPoint: 1115,
    boilingPoint: 1757,
    density: 1.55,
    electronegativity: 1.0,
    stateAtSTP: "solid",
    discoverer: "Humphry Davy",
    discoveryYear: 1808,
    summary: "An essential element for cellular signaling, bone structures, and shell formations.",
    shellConfig: "[Ar] 4s²"
  },
  {
    number: 21,
    symbol: "Sc",
    name: "Scandium",
    mass: 44.956,
    category: "transition-metal",
    shells: [2, 8, 9, 2],
    period: 4,
    group: 3,
    meltingPoint: 1814,
    boilingPoint: 3109,
    density: 2.985,
    electronegativity: 1.36,
    stateAtSTP: "solid",
    discoverer: "Lars Fredrik Nilson",
    discoveryYear: 1879,
    summary: "Historically classified as a rare-earth element, used in high-strength aluminum alloys.",
    shellConfig: "[Ar] 3d¹ 4s²"
  },
  {
    number: 22,
    symbol: "Ti",
    name: "Titanium",
    mass: 47.867,
    category: "transition-metal",
    shells: [2, 8, 10, 2],
    period: 4,
    group: 4,
    meltingPoint: 1941,
    boilingPoint: 3560,
    density: 4.506,
    electronegativity: 1.54,
    stateAtSTP: "solid",
    discoverer: "William Gregor",
    discoveryYear: 1791,
    summary: "Highly prized metal for its low density, extremely high strength, and resistance to corrosion.",
    shellConfig: "[Ar] 3d² 4s²"
  },
  {
    number: 23,
    symbol: "V",
    name: "Vanadium",
    mass: 50.942,
    category: "transition-metal",
    shells: [2, 8, 11, 2],
    period: 4,
    group: 5,
    meltingPoint: 2183,
    boilingPoint: 3680,
    density: 6.11,
    electronegativity: 1.63,
    stateAtSTP: "solid",
    discoverer: "Andrés Manuel del Río",
    discoveryYear: 1801,
    summary: "Hard, ductile, silvery-grey metal used primarily as an additive in steel alloys.",
    shellConfig: "[Ar] 3d³ 4s²"
  },
  {
    number: 24,
    symbol: "Cr",
    name: "Chromium",
    mass: 51.996,
    category: "transition-metal",
    shells: [2, 8, 13, 1],
    period: 4,
    group: 6,
    meltingPoint: 2180,
    boilingPoint: 2944,
    density: 7.19,
    electronegativity: 1.66,
    stateAtSTP: "solid",
    discoverer: "Louis Nicolas Vauquelin",
    discoveryYear: 1797,
    summary: "Steely-gray, lustrous metal that takes a high polish. Famous for chrome plating.",
    shellConfig: "[Ar] 3d⁵ 4s¹"
  },
  {
    number: 25,
    symbol: "Mn",
    name: "Manganese",
    mass: 54.938,
    category: "transition-metal",
    shells: [2, 8, 13, 2],
    period: 4,
    group: 7,
    meltingPoint: 1519,
    boilingPoint: 2334,
    density: 7.21,
    electronegativity: 1.55,
    stateAtSTP: "solid",
    discoverer: "Carl Wilhelm Scheele",
    discoveryYear: 1774,
    summary: "A metal with critical industrial alloys uses, particularly in stainless steels.",
    shellConfig: "[Ar] 3d⁵ 4s²"
  },
  {
    number: 26,
    symbol: "Fe",
    name: "Iron",
    mass: 55.845,
    category: "transition-metal",
    shells: [2, 8, 14, 2],
    period: 4,
    group: 8,
    meltingPoint: 1811,
    boilingPoint: 3134,
    density: 7.874,
    electronegativity: 1.83,
    stateAtSTP: "solid",
    discoverer: "Before 5000 BCE",
    discoveryYear: "Unknown",
    summary: "By mass the most common element on Earth, forming much of Earth's outer and inner core.",
    shellConfig: "[Ar] 3d⁶ 4s²"
  },
  {
    number: 27,
    symbol: "Co",
    name: "Cobalt",
    mass: 58.933,
    category: "transition-metal",
    shells: [2, 8, 15, 2],
    period: 4,
    group: 9,
    meltingPoint: 1768,
    boilingPoint: 3200,
    density: 8.9,
    electronegativity: 1.88,
    stateAtSTP: "solid",
    discoverer: "Georg Brandt",
    discoveryYear: 1735,
    summary: "Lustrous, magnetic metal used in powerful superalloys and lithium-ion batteries.",
    shellConfig: "[Ar] 3d⁷ 4s²"
  },
  {
    number: 28,
    symbol: "Ni",
    name: "Nickel",
    mass: 58.693,
    category: "transition-metal",
    shells: [2, 8, 16, 2],
    period: 4,
    group: 10,
    meltingPoint: 1728,
    boilingPoint: 3186,
    density: 8.908,
    electronegativity: 1.91,
    stateAtSTP: "solid",
    discoverer: "Axel Fredrik Cronstedt",
    discoveryYear: 1751,
    summary: "Silvery-white lustrous metal with a slight golden tinge, highly corrosion-resistant.",
    shellConfig: "[Ar] 3d⁸ 4s²"
  },
  {
    number: 29,
    symbol: "Cu",
    name: "Copper",
    mass: 63.546,
    category: "transition-metal",
    shells: [2, 8, 18, 1],
    period: 4,
    group: 11,
    meltingPoint: 1357.77,
    boilingPoint: 2835,
    density: 8.96,
    electronegativity: 1.9,
    stateAtSTP: "solid",
    discoverer: "Middle East",
    discoveryYear: "9000 BCE",
    summary: "A soft, malleable, and ductile metal with very high thermal and electrical conductivity.",
    shellConfig: "[Ar] 3d¹⁰ 4s¹"
  },
  {
    number: 30,
    symbol: "Zn",
    name: "Zinc",
    mass: 65.38,
    category: "transition-metal",
    shells: [2, 8, 18, 2],
    period: 4,
    group: 12,
    meltingPoint: 692.68,
    boilingPoint: 1180,
    density: 7.14,
    electronegativity: 1.65,
    stateAtSTP: "solid",
    discoverer: "Indian Chemists",
    discoveryYear: "Before 1000 BCE",
    summary: "Slightly brittle metal at room temperature, widely used in galvanizing steel to prevent rust.",
    shellConfig: "[Ar] 3d¹⁰ 4s²"
  },
  {
    number: 31,
    symbol: "Ga",
    name: "Gallium",
    mass: 69.723,
    category: "post-transition-metal",
    shells: [2, 8, 18, 3],
    period: 4,
    group: 13,
    meltingPoint: 302.91,
    boilingPoint: 2673,
    density: 5.91,
    electronegativity: 1.81,
    stateAtSTP: "solid",
    discoverer: "Paul-Émile Lecoq de Boisbaudran",
    discoveryYear: 1875,
    summary: "Has a melting point close to room temperature (29.76°C) and will literally melt in a warm hand.",
    shellConfig: "[Ar] 3d¹⁰ 4s² 4p¹"
  },
  {
    number: 32,
    symbol: "Ge",
    name: "Germanium",
    mass: 72.63,
    category: "metalloid",
    shells: [2, 8, 18, 4],
    period: 4,
    group: 14,
    meltingPoint: 1211.4,
    boilingPoint: 3106,
    density: 5.323,
    electronegativity: 2.01,
    stateAtSTP: "solid",
    discoverer: "Clemens Winkler",
    discoveryYear: 1886,
    summary: "Lustrous, hard-brittle, grayish-white metalloid chemically similar to silicon and tin.",
    shellConfig: "[Ar] 3d¹⁰ 4s² 4p²"
  },
  {
    number: 33,
    symbol: "As",
    name: "Arsenic",
    mass: 74.922,
    category: "metalloid",
    shells: [2, 8, 18, 5],
    period: 4,
    group: 15,
    meltingPoint: 1090,
    boilingPoint: 887,
    density: 5.727,
    electronegativity: 2.18,
    stateAtSTP: "solid",
    discoverer: "Albertus Magnus",
    discoveryYear: 1250,
    summary: "Infamous for its extreme toxicity, historically used in poisons, wood preservatives, and pesticides.",
    shellConfig: "[Ar] 3d¹⁰ 4s² 4p³"
  },
  {
    number: 34,
    symbol: "Se",
    name: "Selenium",
    mass: 78.971,
    category: "reactive-nonmetal",
    shells: [2, 8, 18, 6],
    period: 4,
    group: 16,
    meltingPoint: 494,
    boilingPoint: 958,
    density: 4.81,
    electronegativity: 2.55,
    stateAtSTP: "solid",
    discoverer: "Jöns Jacob Berzelius",
    discoveryYear: 1817,
    summary: "A nonmetal that exhibits photovoltaic properties (converts light directly into electricity).",
    shellConfig: "[Ar] 3d¹⁰ 4s² 4p⁴"
  },
  {
    number: 35,
    symbol: "Br",
    name: "Bromine",
    mass: 79.904,
    category: "reactive-nonmetal",
    shells: [2, 8, 18, 7],
    period: 4,
    group: 17,
    meltingPoint: 265.8,
    boilingPoint: 332,
    density: 3.1028,
    electronegativity: 2.96,
    stateAtSTP: "liquid",
    discoverer: "Balard & Löwig",
    discoveryYear: 1825,
    summary: "The only nonmetallic element that is a liquid under standard conditions, evaporating into toxic red vapor.",
    shellConfig: "[Ar] 3d¹⁰ 4s² 4p⁵"
  },
  {
    number: 36,
    symbol: "Kr",
    name: "Krypton",
    mass: 83.798,
    category: "noble-gas",
    shells: [2, 8, 18, 8],
    period: 4,
    group: 18,
    meltingPoint: 115.79,
    boilingPoint: 119.93,
    density: 0.003733,
    electronegativity: 3.0,
    stateAtSTP: "gas",
    discoverer: "Ramsay & Travers",
    discoveryYear: 1898,
    summary: "A noble gas used in high-speed photographic flashes and high-efficiency fluorescent bulbs.",
    shellConfig: "[Ar] 3d¹⁰ 4s² 4p⁶"
  },
  {
    number: 37,
    symbol: "Rb",
    name: "Rubidium",
    mass: 85.468,
    category: "alkali-metal",
    shells: [2, 8, 18, 8, 1],
    period: 5,
    group: 1,
    meltingPoint: 312.46,
    boilingPoint: 961,
    density: 1.532,
    electronegativity: 0.82,
    stateAtSTP: "solid",
    discoverer: "Bunsen & Kirchhoff",
    discoveryYear: 1861,
    summary: "An extremely soft, silvery-white alkali metal that ignites spontaneously in air.",
    shellConfig: "[Kr] 5s¹"
  },
  {
    number: 38,
    symbol: "Sr",
    name: "Strontium",
    mass: 87.62,
    category: "alkaline-earth-metal",
    shells: [2, 8, 18, 8, 2],
    period: 5,
    group: 2,
    meltingPoint: 1050,
    boilingPoint: 1655,
    density: 2.64,
    electronegativity: 0.95,
    stateAtSTP: "solid",
    discoverer: "Adair Crawford",
    discoveryYear: 1790,
    summary: "Highly chemically reactive; burns with a bright crimson flame in air, used in fireworks.",
    shellConfig: "[Kr] 5s²"
  },
  {
    number: 39,
    symbol: "Y",
    name: "Yttrium",
    mass: 88.906,
    category: "transition-metal",
    shells: [2, 8, 18, 9, 2],
    period: 5,
    group: 3,
    meltingPoint: 1799,
    boilingPoint: 3609,
    density: 4.472,
    electronegativity: 1.22,
    stateAtSTP: "solid",
    discoverer: "Johan Gadolin",
    discoveryYear: 1794,
    summary: "Silvery-metallic transition metal, historically used as phosphors for red colors in CRT televisions.",
    shellConfig: "[Kr] 4d¹ 5s²"
  },
  {
    number: 40,
    symbol: "Zr",
    name: "Zirconium",
    mass: 91.224,
    category: "transition-metal",
    shells: [2, 8, 18, 10, 2],
    period: 5,
    group: 4,
    meltingPoint: 2128,
    boilingPoint: 4682,
    density: 6.52,
    electronegativity: 1.33,
    stateAtSTP: "solid",
    discoverer: "Martin Heinrich Klaproth",
    discoveryYear: 1789,
    summary: "Lustrous, greyish-white, strong metal resembling hafnium and titanium. Used in nuclear reactors.",
    shellConfig: "[Kr] 4d² 5s²"
  },
  {
    number: 41,
    symbol: "Nb",
    name: "Niobium",
    mass: 92.906,
    category: "transition-metal",
    shells: [2, 8, 18, 12, 1],
    period: 5,
    group: 5,
    meltingPoint: 2750,
    boilingPoint: 5017,
    density: 8.57,
    electronegativity: 1.6,
    stateAtSTP: "solid",
    discoverer: "Charles Hatchett",
    discoveryYear: 1801,
    summary: "A light grey, crystalline, ductile transition metal, highly prized for superconductive alloys.",
    shellConfig: "[Kr] 4d⁴ 5s¹"
  },
  {
    number: 42,
    symbol: "Mo",
    name: "Molybdenum",
    mass: 95.95,
    category: "transition-metal",
    shells: [2, 8, 18, 13, 1],
    period: 5,
    group: 6,
    meltingPoint: 2896,
    boilingPoint: 4912,
    density: 10.28,
    electronegativity: 2.16,
    stateAtSTP: "solid",
    discoverer: "Carl Wilhelm Scheele",
    discoveryYear: 1778,
    summary: "Has one of the highest melting points of all pure elements, used in structural steel alloys.",
    shellConfig: "[Kr] 4d⁵ 5s¹"
  },
  {
    number: 43,
    symbol: "Tc",
    name: "Technetium",
    mass: 98,
    category: "transition-metal",
    shells: [2, 8, 18, 13, 2],
    period: 5,
    group: 7,
    meltingPoint: 2430,
    boilingPoint: 4538,
    density: 11,
    electronegativity: 1.9,
    stateAtSTP: "solid",
    discoverer: "Segrè & Perrier",
    discoveryYear: 1937,
    summary: "The lightest chemical element whose isotopes are all radioactive; virtually entirely synthetic.",
    shellConfig: "[Kr] 4d⁵ 5s²"
  },
  {
    number: 44,
    symbol: "Ru",
    name: "Ruthenium",
    mass: 101.07,
    category: "transition-metal",
    shells: [2, 8, 18, 15, 1],
    period: 5,
    group: 8,
    meltingPoint: 2607,
    boilingPoint: 4423,
    density: 12.45,
    electronegativity: 2.2,
    stateAtSTP: "solid",
    discoverer: "Karl Ernst Claus",
    discoveryYear: 1844,
    summary: "Rare transition metal belonging to the platinum group. Highly inert to most chemicals.",
    shellConfig: "[Kr] 4d⁷ 5s¹"
  },
  {
    number: 45,
    symbol: "Rh",
    name: "Rhodium",
    mass: 102.91,
    category: "transition-metal",
    shells: [2, 8, 18, 16, 1],
    period: 5,
    group: 9,
    meltingPoint: 2237,
    boilingPoint: 3968,
    density: 12.41,
    electronegativity: 2.28,
    stateAtSTP: "solid",
    discoverer: "William Hyde Wollaston",
    discoveryYear: 1803,
    summary: "Extremely rare, valuable, silvery-white, and corrosion-resistant noble transition metal.",
    shellConfig: "[Kr] 4d⁸ 5s¹"
  },
  {
    number: 46,
    symbol: "Pd",
    name: "Palladium",
    mass: 106.42,
    category: "transition-metal",
    shells: [2, 8, 18, 18],
    period: 5,
    group: 10,
    meltingPoint: 1828.05,
    boilingPoint: 3236,
    density: 12.023,
    electronegativity: 2.2,
    stateAtSTP: "solid",
    discoverer: "William Hyde Wollaston",
    discoveryYear: 1803,
    summary: "Lustrous silvery metal that absorbs up to 900 times its volume of hydrogen gas at room temp.",
    shellConfig: "[Kr] 4d¹⁰"
  },
  {
    number: 47,
    symbol: "Ag",
    name: "Silver",
    mass: 107.87,
    category: "transition-metal",
    shells: [2, 8, 18, 18, 1],
    period: 5,
    group: 11,
    meltingPoint: 1234.93,
    boilingPoint: 2435,
    density: 10.49,
    electronegativity: 1.93,
    stateAtSTP: "solid",
    discoverer: "Prehistoric Societies",
    discoveryYear: "Unknown",
    summary: "Exhibits the highest electrical conductivity, thermal conductivity, and reflectivity of any metal.",
    shellConfig: "[Kr] 4d¹⁰ 5s¹"
  },
  {
    number: 48,
    symbol: "Cd",
    name: "Cadmium",
    mass: 112.41,
    category: "transition-metal",
    shells: [2, 8, 18, 18, 2],
    period: 5,
    group: 12,
    meltingPoint: 594.22,
    boilingPoint: 1040,
    density: 8.65,
    electronegativity: 1.69,
    stateAtSTP: "solid",
    discoverer: "Stromeyer & Hermann",
    discoveryYear: 1817,
    summary: "A soft, bluish-white metal, highly toxic, historically used in pigments and electroplating.",
    shellConfig: "[Kr] 4d¹⁰ 5s²"
  },
  {
    number: 49,
    symbol: "In",
    name: "Indium",
    mass: 114.82,
    category: "post-transition-metal",
    shells: [2, 8, 18, 18, 3],
    period: 5,
    group: 13,
    meltingPoint: 429.75,
    boilingPoint: 2270,
    density: 7.31,
    electronegativity: 1.78,
    stateAtSTP: "solid",
    discoverer: "Reich & Richter",
    discoveryYear: 1863,
    summary: "A very soft, malleable metal. Crucial for touchscreens when processed into Indium Tin Oxide (ITO).",
    shellConfig: "[Kr] 4d¹⁰ 5s² 5p¹"
  },
  {
    number: 50,
    symbol: "Sn",
    name: "Tin",
    mass: 118.71,
    category: "post-transition-metal",
    shells: [2, 8, 18, 18, 4],
    period: 5,
    group: 14,
    meltingPoint: 505.08,
    boilingPoint: 2875,
    density: 7.287,
    electronegativity: 1.96,
    stateAtSTP: "solid",
    discoverer: "Ancient Civilizations",
    discoveryYear: "3000 BCE",
    summary: "A silvery metal famously alloyed with copper to create bronze, ushering in the Bronze Age.",
    shellConfig: "[Kr] 4d¹⁰ 5s² 5p²"
  },
  {
    number: 51,
    symbol: "Sb",
    name: "Antimony",
    mass: 121.76,
    category: "metalloid",
    shells: [2, 8, 18, 18, 5],
    period: 5,
    group: 15,
    meltingPoint: 903.78,
    boilingPoint: 1860,
    density: 6.697,
    electronegativity: 2.05,
    stateAtSTP: "solid",
    discoverer: "Ancient Egypt",
    discoveryYear: "Before 3000 BCE",
    summary: "Lustrous gray metalloid found in nature as stibnite. Used in flame-proofing compounds.",
    shellConfig: "[Kr] 4d¹⁰ 5s² 5p³"
  },
  {
    number: 52,
    symbol: "Te",
    name: "Tellurium",
    mass: 127.6,
    category: "metalloid",
    shells: [2, 8, 18, 18, 6],
    period: 5,
    group: 16,
    meltingPoint: 722.66,
    boilingPoint: 1261,
    density: 6.24,
    electronegativity: 2.1,
    stateAtSTP: "solid",
    discoverer: "Franz-Joseph Müller von Reichenstein",
    discoveryYear: 1782,
    summary: "A brittle, mildly toxic, rare silver-white metalloid. Extensively used in solar panels.",
    shellConfig: "[Kr] 4d¹⁰ 5s² 5p⁴"
  },
  {
    number: 53,
    symbol: "I",
    name: "Iodine",
    mass: 126.9,
    category: "reactive-nonmetal",
    shells: [2, 8, 18, 18, 7],
    period: 5,
    group: 17,
    meltingPoint: 386.85,
    boilingPoint: 457.4,
    density: 4.933,
    electronegativity: 2.66,
    stateAtSTP: "solid",
    discoverer: "Bernard Courtois",
    discoveryYear: 1811,
    summary: "Lustrous purple-black solid nonmetal that sublimates into a highly irritant violet gas.",
    shellConfig: "[Kr] 4d¹⁰ 5s² 5p⁵"
  },
  {
    number: 54,
    symbol: "Xe",
    name: "Xenon",
    mass: 131.29,
    category: "noble-gas",
    shells: [2, 8, 18, 18, 8],
    period: 5,
    group: 18,
    meltingPoint: 161.4,
    boilingPoint: 165.03,
    density: 0.005894,
    electronegativity: 2.6,
    stateAtSTP: "gas",
    discoverer: "Ramsay & Travers",
    discoveryYear: 1898,
    summary: "An extremely dense noble gas, used in specialized flash lamps and ion thrusters for spacecraft.",
    shellConfig: "[Kr] 4d¹⁰ 5s² 5p⁶"
  },
  {
    number: 55,
    symbol: "Cs",
    name: "Cesium",
    mass: 132.91,
    category: "alkali-metal",
    shells: [2, 8, 18, 18, 8, 1],
    period: 6,
    group: 1,
    meltingPoint: 301.59,
    boilingPoint: 944,
    density: 1.93,
    electronegativity: 0.79,
    stateAtSTP: "solid",
    discoverer: "Bunsen & Kirchhoff",
    discoveryYear: 1860,
    summary: "Soft gold-tinted alkali metal. The vibration frequency of Cs-133 defines the standard 'second'.",
    shellConfig: "[Xe] 6s¹"
  },
  {
    number: 56,
    symbol: "Ba",
    name: "Barium",
    mass: 137.33,
    category: "alkaline-earth-metal",
    shells: [2, 8, 18, 18, 8, 2],
    period: 6,
    group: 2,
    meltingPoint: 1000,
    boilingPoint: 2170,
    density: 3.51,
    electronegativity: 0.89,
    stateAtSTP: "solid",
    discoverer: "Carl Wilhelm Scheele",
    discoveryYear: 1772,
    summary: "Soft, silvery alkaline earth metal. Because of high reactivity, it is never found as a free element.",
    shellConfig: "[Xe] 6s²"
  },
  {
    number: 57,
    symbol: "La",
    name: "Lanthanum",
    mass: 138.91,
    category: "lanthanide",
    shells: [2, 8, 18, 18, 9, 2],
    period: 6,
    group: null,
    meltingPoint: 1193,
    boilingPoint: 3737,
    density: 6.162,
    electronegativity: 1.1,
    stateAtSTP: "solid",
    discoverer: "Carl Gustaf Mosander",
    discoveryYear: 1839,
    summary: "The prototype of the lanthanide series. Highly malleable and soft enough to be cut with a knife.",
    shellConfig: "[Xe] 5d¹ 6s²"
  },
  {
    number: 58,
    symbol: "Ce",
    name: "Cerium",
    mass: 140.12,
    category: "lanthanide",
    shells: [2, 8, 18, 19, 9, 2],
    period: 6,
    group: null,
    meltingPoint: 1068,
    boilingPoint: 3716,
    density: 6.77,
    electronegativity: 1.12,
    stateAtSTP: "solid",
    discoverer: "Martin Heinrich Klaproth",
    discoveryYear: 1803,
    summary: "A soft, ductile, silvery metal that oxidizes exceptionally fast in air. Major sparker in lighters.",
    shellConfig: "[Xe] 4f¹ 5d¹ 6s²"
  },
  {
    number: 59,
    symbol: "Pr",
    name: "Praseodymium",
    mass: 140.91,
    category: "lanthanide",
    shells: [2, 8, 18, 21, 8, 2],
    period: 6,
    group: null,
    meltingPoint: 1208,
    boilingPoint: 3793,
    density: 6.77,
    electronegativity: 1.13,
    stateAtSTP: "solid",
    discoverer: "Carl Auer von Welsbach",
    discoveryYear: 1885,
    summary: "Soft, ductile, silvery metal, famous for creating brilliant yellow colors in glasses and goggles.",
    shellConfig: "[Xe] 4f³ 6s²"
  },
  {
    number: 60,
    symbol: "Nd",
    name: "Neodymium",
    mass: 144.24,
    category: "lanthanide",
    shells: [2, 8, 18, 22, 8, 2],
    period: 6,
    group: null,
    meltingPoint: 1297,
    boilingPoint: 3347,
    density: 7.01,
    electronegativity: 1.14,
    stateAtSTP: "solid",
    discoverer: "Carl Auer von Welsbach",
    discoveryYear: 1885,
    summary: "Silvery metal, widely alloyed to manufacture the strongest permanent magnets commercially available.",
    shellConfig: "[Xe] 4f⁴ 6s²"
  },
  {
    number: 61,
    symbol: "Pm",
    name: "Promethium",
    mass: 145,
    category: "lanthanide",
    shells: [2, 8, 18, 23, 8, 2],
    period: 6,
    group: null,
    meltingPoint: 1315,
    boilingPoint: 3273,
    density: 7.26,
    electronegativity: 1.13,
    stateAtSTP: "solid",
    discoverer: "Marinsky, Glendenin & Coryell",
    discoveryYear: 1945,
    summary: "Extremely rare radioactive element. All its isotopes are unstable and decay with beta emission.",
    shellConfig: "[Xe] 4f⁵ 6s²"
  },
  {
    number: 62,
    symbol: "Sm",
    name: "Samarium",
    mass: 150.36,
    category: "lanthanide",
    shells: [2, 8, 18, 24, 8, 2],
    period: 6,
    group: null,
    meltingPoint: 1347,
    boilingPoint: 2067,
    density: 7.52,
    electronegativity: 1.17,
    stateAtSTP: "solid",
    discoverer: "Paul-Émile Lecoq de Boisbaudran",
    discoveryYear: 1879,
    summary: "Silvery metal, used in high-temp Samarium-Cobalt magnets and as a catalyst in organic chemistry.",
    shellConfig: "[Xe] 4f⁶ 6s²"
  },
  {
    number: 63,
    symbol: "Eu",
    name: "Europium",
    mass: 151.96,
    category: "lanthanide",
    shells: [2, 8, 18, 25, 8, 2],
    period: 6,
    group: null,
    meltingPoint: 1099,
    boilingPoint: 1802,
    density: 5.264,
    electronegativity: 1.2,
    stateAtSTP: "solid",
    discoverer: "Eugène-Anatole Demarçay",
    discoveryYear: 1901,
    summary: "The most highly reactive lanthanide; glows with a bright red color in cathode ray tube phosphors.",
    shellConfig: "[Xe] 4f⁷ 6s²"
  },
  {
    number: 64,
    symbol: "Gd",
    name: "Gadolinium",
    mass: 157.25,
    category: "lanthanide",
    shells: [2, 8, 18, 25, 9, 2],
    period: 6,
    group: null,
    meltingPoint: 1585,
    boilingPoint: 3546,
    density: 7.9,
    electronegativity: 1.2,
    stateAtSTP: "solid",
    discoverer: "Jean Charles Galissard de Marignac",
    discoveryYear: 1880,
    summary: "Has exceptionally high thermal neutron absorption, widely used as a contrast agent in MRI scans.",
    shellConfig: "[Xe] 4f⁷ 5d¹ 6s²"
  },
  {
    number: 65,
    symbol: "Tb",
    name: "Terbium",
    mass: 158.93,
    category: "lanthanide",
    shells: [2, 8, 18, 27, 8, 2],
    period: 6,
    group: null,
    meltingPoint: 1629,
    boilingPoint: 3503,
    density: 8.23,
    electronegativity: 1.1,
    stateAtSTP: "solid",
    discoverer: "Carl Gustaf Mosander",
    discoveryYear: 1843,
    summary: "Silvery-gray rare earth metal that can be cut with a knife. Used in solid-state devices.",
    shellConfig: "[Xe] 4f⁹ 6s²"
  },
  {
    number: 66,
    symbol: "Dy",
    name: "Dysprosium",
    mass: 162.5,
    category: "lanthanide",
    shells: [2, 8, 18, 28, 8, 2],
    period: 6,
    group: null,
    meltingPoint: 1680,
    boilingPoint: 2840,
    density: 8.54,
    electronegativity: 1.22,
    stateAtSTP: "solid",
    discoverer: "Paul-Émile Lecoq de Boisbaudran",
    discoveryYear: 1886,
    summary: "Extremely magnetic at low temperatures; primarily used in neodymium magnets to prevent demagnetization.",
    shellConfig: "[Xe] 4f¹⁰ 6s²"
  },
  {
    number: 67,
    symbol: "Ho",
    name: "Holmium",
    mass: 164.93,
    category: "lanthanide",
    shells: [2, 8, 18, 29, 8, 2],
    period: 6,
    group: null,
    meltingPoint: 1734,
    boilingPoint: 2993,
    density: 8.79,
    electronegativity: 1.23,
    stateAtSTP: "solid",
    discoverer: "Marc Delafontaine",
    discoveryYear: 1878,
    summary: "Possesses the highest magnetic strength (magnetic moment) of any element on the periodic table.",
    shellConfig: "[Xe] 4f¹¹ 6s²"
  },
  {
    number: 68,
    symbol: "Er",
    name: "Erbium",
    mass: 167.26,
    category: "lanthanide",
    shells: [2, 8, 18, 30, 8, 2],
    period: 6,
    group: null,
    meltingPoint: 1802,
    boilingPoint: 3141,
    density: 9.066,
    electronegativity: 1.24,
    stateAtSTP: "solid",
    discoverer: "Carl Gustaf Mosander",
    discoveryYear: 1843,
    summary: "Silvery-white solid, extensively used in fiber-optic communications as a signal amplifier (EDFA).",
    shellConfig: "[Xe] 4f¹² 6s²"
  },
  {
    number: 69,
    symbol: "Tm",
    name: "Thulium",
    mass: 168.93,
    category: "lanthanide",
    shells: [2, 8, 18, 31, 8, 2],
    period: 6,
    group: null,
    meltingPoint: 1818,
    boilingPoint: 2223,
    density: 9.32,
    electronegativity: 1.25,
    stateAtSTP: "solid",
    discoverer: "Per Teodor Cleve",
    discoveryYear: 1879,
    summary: "The second least abundant lanthanide. Highly valuable, used in portable medical X-ray machines.",
    shellConfig: "[Xe] 4f¹³ 6s²"
  },
  {
    number: 70,
    symbol: "Yb",
    name: "Ytterbium",
    mass: 173.05,
    category: "lanthanide",
    shells: [2, 8, 18, 32, 8, 2],
    period: 6,
    group: null,
    meltingPoint: 1097,
    boilingPoint: 1469,
    density: 6.9,
    electronegativity: 1.1,
    stateAtSTP: "solid",
    discoverer: "Jean Charles Galissard de Marignac",
    discoveryYear: 1878,
    summary: "Soft, malleable lanthanide. Used in ultra-precise atomic clocks and high-stress steel sensors.",
    shellConfig: "[Xe] 4f¹⁴ 6s²"
  },
  {
    number: 71,
    symbol: "Lu",
    name: "Lutetium",
    mass: 174.97,
    category: "lanthanide",
    shells: [2, 8, 18, 32, 9, 2],
    period: 6,
    group: 3,
    meltingPoint: 1925,
    boilingPoint: 3675,
    density: 9.841,
    electronegativity: 1.27,
    stateAtSTP: "solid",
    discoverer: "Georges Urbain",
    discoveryYear: 1907,
    summary: "The densest and hardest lanthanide, highly expensive and technically difficult to isolate.",
    shellConfig: "[Xe] 4f¹⁴ 5d¹ 6s²"
  },
  {
    number: 72,
    symbol: "Hf",
    name: "Hafnium",
    mass: 178.49,
    category: "transition-metal",
    shells: [2, 8, 18, 32, 10, 2],
    period: 6,
    group: 4,
    meltingPoint: 2506,
    boilingPoint: 4876,
    density: 13.31,
    electronegativity: 1.3,
    stateAtSTP: "solid",
    discoverer: "Coster & Hevesy",
    discoveryYear: 1923,
    summary: "Lustrous, silvery-gray metal that absorbs neutrons perfectly; used in nuclear control rods.",
    shellConfig: "[Xe] 4f¹⁴ 5d² 6s²"
  },
  {
    number: 73,
    symbol: "Ta",
    name: "Tantalum",
    mass: 180.95,
    category: "transition-metal",
    shells: [2, 8, 18, 32, 11, 2],
    period: 6,
    group: 5,
    meltingPoint: 3290,
    boilingPoint: 5731,
    density: 16.69,
    electronegativity: 1.5,
    stateAtSTP: "solid",
    discoverer: "Anders Gustaf Ekeberg",
    discoveryYear: 1802,
    summary: "Highly corrosion-resistant, blue-grey metal. Critical for high-capacitance miniature cell phone capacitors.",
    shellConfig: "[Xe] 4f¹⁴ 5d³ 6s²"
  },
  {
    number: 74,
    symbol: "W",
    name: "Tungsten",
    mass: 183.84,
    category: "transition-metal",
    shells: [2, 8, 18, 32, 12, 2],
    period: 6,
    group: 6,
    meltingPoint: 3695,
    boilingPoint: 6203,
    density: 19.25,
    electronegativity: 2.36,
    stateAtSTP: "solid",
    discoverer: "Carl Wilhelm Scheele",
    discoveryYear: 1781,
    summary: "Has the highest melting point of all elements. Also known as Wolfram, historically used in lightbulbs.",
    shellConfig: "[Xe] 4f¹⁴ 5d⁴ 6s²"
  },
  {
    number: 75,
    symbol: "Re",
    name: "Rhenium",
    mass: 186.21,
    category: "transition-metal",
    shells: [2, 8, 18, 32, 13, 2],
    period: 6,
    group: 7,
    meltingPoint: 3459,
    boilingPoint: 5869,
    density: 21.02,
    electronegativity: 1.9,
    stateAtSTP: "solid",
    discoverer: "Noddack, Tacke & Berg",
    discoveryYear: 1925,
    summary: "Extremely rare transition metal with high density. Heavily used in jet engine turbine blades.",
    shellConfig: "[Xe] 4f¹⁴ 5d⁵ 6s²"
  },
  {
    number: 76,
    symbol: "Os",
    name: "Osmium",
    mass: 190.23,
    category: "transition-metal",
    shells: [2, 8, 18, 32, 14, 2],
    period: 6,
    group: 8,
    meltingPoint: 3306,
    boilingPoint: 5285,
    density: 22.59,
    electronegativity: 2.2,
    stateAtSTP: "solid",
    discoverer: "Smithson Tennant",
    discoveryYear: 1803,
    summary: "The densest naturally occurring element. Extremely hard, brittle, blue-gray transition metal.",
    shellConfig: "[Xe] 4f¹⁴ 5d⁶ 6s²"
  },
  {
    number: 77,
    symbol: "Ir",
    name: "Iridium",
    mass: 192.22,
    category: "transition-metal",
    shells: [2, 8, 18, 32, 15, 2],
    period: 6,
    group: 9,
    meltingPoint: 2719,
    boilingPoint: 4701,
    density: 22.56,
    electronegativity: 2.2,
    stateAtSTP: "solid",
    discoverer: "Smithson Tennant",
    discoveryYear: 1803,
    summary: "The second-densest element. Famous for its high concentration in the KT boundary clay layer (asteroid impact).",
    shellConfig: "[Xe] 4f¹⁴ 5d⁷ 6s²"
  },
  {
    number: 78,
    symbol: "Pt",
    name: "Platinum",
    mass: 195.08,
    category: "transition-metal",
    shells: [2, 8, 18, 32, 17, 1],
    period: 6,
    group: 10,
    meltingPoint: 2041.4,
    boilingPoint: 4098,
    density: 21.45,
    electronegativity: 2.28,
    stateAtSTP: "solid",
    discoverer: "Antonio de Ulloa",
    discoveryYear: 1735,
    summary: "Extremely precious, ductile, and dense noble metal. Heavily used in vehicle catalytic converters.",
    shellConfig: "[Xe] 4f¹⁴ 5d⁹ 6s¹"
  },
  {
    number: 79,
    symbol: "Au",
    name: "Gold",
    mass: 196.97,
    category: "transition-metal",
    shells: [2, 8, 18, 32, 18, 1],
    period: 6,
    group: 11,
    meltingPoint: 1337.33,
    boilingPoint: 3129,
    density: 19.3,
    electronegativity: 2.54,
    stateAtSTP: "solid",
    discoverer: "Prehistoric Civilizations",
    discoveryYear: "Before 3000 BCE",
    summary: "Highly prized precious metal since antiquity. Extremely malleable, conducting electricity perfectly.",
    shellConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s¹"
  },
  {
    number: 80,
    symbol: "Hg",
    name: "Mercury",
    mass: 200.59,
    category: "transition-metal",
    shells: [2, 8, 18, 32, 18, 2],
    period: 6,
    group: 12,
    meltingPoint: 234.32,
    boilingPoint: 629.88,
    density: 13.534,
    electronegativity: 2.0,
    stateAtSTP: "liquid",
    discoverer: "Ancient Egyptians",
    discoveryYear: "1500 BCE",
    summary: "A heavy, silvery liquid metal, historically named quicksilver. Extremely toxic.",
    shellConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s²"
  },
  {
    number: 81,
    symbol: "Tl",
    name: "Thallium",
    mass: 204.38,
    category: "post-transition-metal",
    shells: [2, 8, 18, 32, 18, 3],
    period: 6,
    group: 13,
    meltingPoint: 577,
    boilingPoint: 1746,
    density: 11.85,
    electronegativity: 1.62,
    stateAtSTP: "solid",
    discoverer: "William Crookes",
    discoveryYear: 1861,
    summary: "A soft, highly toxic metal that tarnishes instantly in air. Formerly popular as a rodenticide.",
    shellConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹"
  },
  {
    number: 82,
    symbol: "Pb",
    name: "Lead",
    mass: 207.2,
    category: "post-transition-metal",
    shells: [2, 8, 18, 32, 18, 4],
    period: 6,
    group: 14,
    meltingPoint: 600.61,
    boilingPoint: 2022,
    density: 11.34,
    electronegativity: 2.33,
    stateAtSTP: "solid",
    discoverer: "Middle East",
    discoveryYear: "7000 BCE",
    summary: "Heavy, soft, highly malleable post-transition metal, toxic to humans but useful in batteries.",
    shellConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²"
  },
  {
    number: 83,
    symbol: "Bi",
    name: "Bismuth",
    mass: 208.98,
    category: "post-transition-metal",
    shells: [2, 8, 18, 32, 18, 5],
    period: 6,
    group: 15,
    meltingPoint: 544.7,
    boilingPoint: 1837,
    density: 9.78,
    electronegativity: 2.02,
    stateAtSTP: "solid",
    discoverer: "Claude François Geoffroy",
    discoveryYear: 1753,
    summary: "Brittle metal with an iridescent oxidized surface showing stair-step crystal patterns.",
    shellConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³"
  },
  {
    number: 84,
    symbol: "Po",
    name: "Polonium",
    mass: 209,
    category: "post-transition-metal",
    shells: [2, 8, 18, 32, 18, 6],
    period: 6,
    group: 16,
    meltingPoint: 527,
    boilingPoint: 1235,
    density: 9.196,
    electronegativity: 2.0,
    stateAtSTP: "solid",
    discoverer: "Marie and Pierre Curie",
    discoveryYear: 1898,
    summary: "Rare and highly radioactive element, emitting extremely intense alpha radiation.",
    shellConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴"
  },
  {
    number: 85,
    symbol: "At",
    name: "Astatine",
    mass: 210,
    category: "metalloid",
    shells: [2, 8, 18, 32, 18, 7],
    period: 6,
    group: 17,
    meltingPoint: 575,
    boilingPoint: 610,
    density: 6.2,
    electronegativity: 2.2,
    stateAtSTP: "solid",
    discoverer: "Corson, MacKenzie & Segrè",
    discoveryYear: 1940,
    summary: "The rarest naturally occurring element on Earth, with a total crust abundance of under 1 gram.",
    shellConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵"
  },
  {
    number: 86,
    symbol: "Rn",
    name: "Radon",
    mass: 222,
    category: "noble-gas",
    shells: [2, 8, 18, 32, 18, 8],
    period: 6,
    group: 18,
    meltingPoint: 202,
    boilingPoint: 211.3,
    density: 0.00973,
    electronegativity: 2.2,
    stateAtSTP: "gas",
    discoverer: "Ernest Rutherford / Dorn",
    discoveryYear: 1899,
    summary: "Radioactive noble gas that occurs naturally through radioactive decay of uranium in soils.",
    shellConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶"
  },
  {
    number: 87,
    symbol: "Fr",
    name: "Francium",
    mass: 223,
    category: "alkali-metal",
    shells: [2, 8, 18, 32, 18, 8, 1],
    period: 7,
    group: 1,
    meltingPoint: 300,
    boilingPoint: 950,
    density: 1.87,
    electronegativity: 0.79,
    stateAtSTP: "solid",
    discoverer: "Marguerite Perey",
    discoveryYear: 1939,
    summary: "Extremely radioactive alkali metal, second rarest element in the Earth's crust after astatine.",
    shellConfig: "[Rn] 7s¹"
  },
  {
    number: 88,
    symbol: "Ra",
    name: "Radium",
    mass: 226,
    category: "alkaline-earth-metal",
    shells: [2, 8, 18, 32, 18, 8, 2],
    period: 7,
    group: 2,
    meltingPoint: 973,
    boilingPoint: 2010,
    density: 5.5,
    electronegativity: 0.9,
    stateAtSTP: "solid",
    discoverer: "Marie and Pierre Curie",
    discoveryYear: 1898,
    summary: "Extremely radioactive, luminesces pale blue. Famous for its historical use in glowing watch dials.",
    shellConfig: "[Rn] 7s²"
  },
  {
    number: 89,
    symbol: "Ac",
    name: "Actinium",
    mass: 227,
    category: "actinide",
    shells: [2, 8, 18, 32, 32, 9, 2],
    period: 7,
    group: null,
    meltingPoint: 1323,
    boilingPoint: 3471,
    density: 10.07,
    electronegativity: 1.1,
    stateAtSTP: "solid",
    discoverer: "Friedrich Oskar Giesel",
    discoveryYear: 1902,
    summary: "A radioactive, soft, silvery-white metal that glows in the dark with an eerie blue light.",
    shellConfig: "[Rn] 6d¹ 7s²"
  },
  {
    number: 90,
    symbol: "Th",
    name: "Thorium",
    mass: 232.04,
    category: "actinide",
    shells: [2, 8, 18, 32, 18, 10, 2],
    period: 7,
    group: null,
    meltingPoint: 2023,
    boilingPoint: 5061,
    density: 11.724,
    electronegativity: 1.3,
    stateAtSTP: "solid",
    discoverer: "Jöns Jacob Berzelius",
    discoveryYear: 1829,
    summary: "A weakly radioactive metal, researched extensively as a safer alternative fuel to uranium in reactors.",
    shellConfig: "[Rn] 6d² 7s²"
  },
  {
    number: 91,
    symbol: "Pa",
    name: "Protactinium",
    mass: 231.04,
    category: "actinide",
    shells: [2, 8, 18, 32, 20, 9, 2],
    period: 7,
    group: null,
    meltingPoint: 1841,
    boilingPoint: 4300,
    density: 15.37,
    electronegativity: 1.5,
    stateAtSTP: "solid",
    discoverer: "Soddy, Cranston & Hahn",
    discoveryYear: 1913,
    summary: "Dense, radioactive metal belonging to the actinides, highly toxic due to its radioactivity.",
    shellConfig: "[Rn] 5f² 6d¹ 7s²"
  },
  {
    number: 92,
    symbol: "U",
    name: "Uranium",
    mass: 238.03,
    category: "actinide",
    shells: [2, 8, 18, 32, 21, 9, 2],
    period: 7,
    group: null,
    meltingPoint: 1405.3,
    boilingPoint: 4404,
    density: 19.05,
    electronegativity: 1.38,
    stateAtSTP: "solid",
    discoverer: "Martin Heinrich Klaproth",
    discoveryYear: 1789,
    summary: "Weakly radioactive metal, highly dense, used as the primary fuel source for nuclear power stations.",
    shellConfig: "[Rn] 5f³ 6d¹ 7s²"
  },
  {
    number: 93,
    symbol: "Np",
    name: "Neptunium",
    mass: 237,
    category: "actinide",
    shells: [2, 8, 18, 32, 22, 9, 2],
    period: 7,
    group: null,
    meltingPoint: 917,
    boilingPoint: 4273,
    density: 20.45,
    electronegativity: 1.36,
    stateAtSTP: "solid",
    discoverer: "McMillan & Abelson",
    discoveryYear: 1940,
    summary: "The first transuranium element synthesized, highly radioactive and dense.",
    shellConfig: "[Rn] 5f⁴ 6d¹ 7s²"
  },
  {
    number: 94,
    symbol: "Pu",
    name: "Plutonium",
    mass: 244,
    category: "actinide",
    shells: [2, 8, 18, 32, 24, 8, 2],
    period: 7,
    group: null,
    meltingPoint: 912.5,
    boilingPoint: 3501,
    density: 19.816,
    electronegativity: 1.28,
    stateAtSTP: "solid",
    discoverer: "Glenn T. Seaborg",
    discoveryYear: 1940,
    summary: "Fissile actinide metal synthesized from uranium, key component in nuclear weapons and RTGs.",
    shellConfig: "[Rn] 5f⁶ 7s²"
  },
  {
    number: 95,
    symbol: "Am",
    name: "Americium",
    mass: 243,
    category: "actinide",
    shells: [2, 8, 18, 32, 25, 8, 2],
    period: 7,
    group: null,
    meltingPoint: 1449,
    boilingPoint: 2880,
    density: 12,
    electronegativity: 1.3,
    stateAtSTP: "solid",
    discoverer: "Glenn T. Seaborg",
    discoveryYear: 1944,
    summary: "A transuranic synthetic element, commonly utilized in household ionization smoke detectors.",
    shellConfig: "[Rn] 5f⁷ 7s²"
  },
  {
    number: 96,
    symbol: "Cm",
    name: "Curium",
    mass: 247,
    category: "actinide",
    shells: [2, 8, 18, 32, 25, 9, 2],
    period: 7,
    group: null,
    meltingPoint: 1613,
    boilingPoint: 3383,
    density: 13.51,
    electronegativity: 1.3,
    stateAtSTP: "solid",
    discoverer: "Glenn T. Seaborg",
    discoveryYear: 1944,
    summary: "Highly radioactive synthetic element named in honor of Marie and Pierre Curie.",
    shellConfig: "[Rn] 5f⁷ 6d¹ 7s²"
  },
  {
    number: 97,
    symbol: "Bk",
    name: "Berkelium",
    mass: 247,
    category: "actinide",
    shells: [2, 8, 18, 32, 27, 8, 2],
    period: 7,
    group: null,
    meltingPoint: 1259,
    boilingPoint: 2900,
    density: 14.78,
    electronegativity: 1.3,
    stateAtSTP: "solid",
    discoverer: "Seaborg, Thompson & Ghiorso",
    discoveryYear: 1949,
    summary: "Synthetic element named after Berkeley, California, the site of its creation.",
    shellConfig: "[Rn] 5f⁹ 7s²"
  },
  {
    number: 98,
    symbol: "Cf",
    name: "Californium",
    mass: 251,
    category: "actinide",
    shells: [2, 8, 18, 32, 28, 8, 2],
    period: 7,
    group: null,
    meltingPoint: 1173,
    boilingPoint: 1743,
    density: 15.1,
    electronegativity: 1.3,
    stateAtSTP: "solid",
    discoverer: "Seaborg, Street & Ghiorso",
    discoveryYear: 1950,
    summary: "A strong neutron emitter, used in metal detectors and to initiate nuclear reactors.",
    shellConfig: "[Rn] 5f¹⁰ 7s²"
  },
  {
    number: 99,
    symbol: "Es",
    name: "Einsteinium",
    mass: 252,
    category: "actinide",
    shells: [2, 8, 18, 32, 29, 8, 2],
    period: 7,
    group: null,
    meltingPoint: 1133,
    boilingPoint: null,
    density: 8.84,
    electronegativity: 1.3,
    stateAtSTP: "solid",
    discoverer: "Albert Ghiorso et al.",
    discoveryYear: 1952,
    summary: "Discovered in the debris of the first thermonuclear bomb explosion (Ivy Mike) in 1952.",
    shellConfig: "[Rn] 5f¹¹ 7s²"
  },
  {
    number: 100,
    symbol: "Fm",
    name: "Fermium",
    mass: 257,
    category: "actinide",
    shells: [2, 8, 18, 32, 30, 8, 2],
    period: 7,
    group: null,
    meltingPoint: 1800,
    boilingPoint: null,
    density: null,
    electronegativity: 1.3,
    stateAtSTP: "solid",
    discoverer: "Albert Ghiorso et al.",
    discoveryYear: 1952,
    summary: "The heaviest element that can be formed by neutron bombardment of lighter elements.",
    shellConfig: "[Rn] 5f¹² 7s²"
  },
  {
    number: 101,
    symbol: "Md",
    name: "Mendelevium",
    mass: 258,
    category: "actinide",
    shells: [2, 8, 18, 32, 31, 8, 2],
    period: 7,
    group: null,
    meltingPoint: 1100,
    boilingPoint: null,
    density: null,
    electronegativity: 1.3,
    stateAtSTP: "solid",
    discoverer: "Albert Ghiorso et al.",
    discoveryYear: 1955,
    summary: "Synthetic element named to honor Dmitri Mendeleev, the father of the periodic table.",
    shellConfig: "[Rn] 5f¹³ 7s²"
  },
  {
    number: 102,
    symbol: "No",
    name: "Nobelium",
    mass: 259,
    category: "actinide",
    shells: [2, 8, 18, 32, 32, 8, 2],
    period: 7,
    group: null,
    meltingPoint: 1100,
    boilingPoint: null,
    density: null,
    electronegativity: 1.3,
    stateAtSTP: "solid",
    discoverer: "Dubna & Berkeley Labs",
    discoveryYear: 1966,
    summary: "Synthetic radioactive element, named after Alfred Nobel, the inventor of dynamite.",
    shellConfig: "[Rn] 5f¹⁴ 7s²"
  },
  {
    number: 103,
    symbol: "Lr",
    name: "Lawrencium",
    mass: 266,
    category: "actinide",
    shells: [2, 8, 18, 32, 32, 9, 2],
    period: 7,
    group: 3,
    meltingPoint: 1900,
    boilingPoint: null,
    density: null,
    electronegativity: 1.3,
    stateAtSTP: "solid",
    discoverer: "Albert Ghiorso et al.",
    discoveryYear: 1961,
    summary: "Named after Ernest Lawrence, inventor of the cyclotron. Highly radioactive synthetic metal.",
    shellConfig: "[Rn] 5f¹⁴ 7s² 7p¹"
  },
  {
    number: 104,
    symbol: "Rf",
    name: "Rutherfordium",
    mass: 267,
    category: "transition-metal",
    shells: [2, 8, 18, 32, 32, 10, 2],
    period: 7,
    group: 4,
    meltingPoint: 2400,
    boilingPoint: 5800,
    density: 23.2,
    electronegativity: null,
    stateAtSTP: "solid",
    discoverer: "Dubna & Berkeley Labs",
    discoveryYear: 1964,
    summary: "Highly radioactive synthetic element with an extremely short half-life.",
    shellConfig: "[Rn] 5f¹⁴ 6d² 7s²"
  },
  {
    number: 105,
    symbol: "Db",
    name: "Dubnium",
    mass: 268,
    category: "transition-metal",
    shells: [2, 8, 18, 32, 32, 11, 2],
    period: 7,
    group: 5,
    meltingPoint: null,
    boilingPoint: null,
    density: 29.3,
    electronegativity: null,
    stateAtSTP: "solid",
    discoverer: "Dubna & Berkeley Labs",
    discoveryYear: 1967,
    summary: "Synthetic element named after Dubna, Russia, where it was first synthesized.",
    shellConfig: "[Rn] 5f¹⁴ 6d³ 7s²"
  },
  {
    number: 106,
    symbol: "Sg",
    name: "Seaborgium",
    mass: 269,
    category: "transition-metal",
    shells: [2, 8, 18, 32, 32, 12, 2],
    period: 7,
    group: 6,
    meltingPoint: null,
    boilingPoint: null,
    density: 35.0,
    electronegativity: null,
    stateAtSTP: "solid",
    discoverer: "Lawrence Berkeley Lab",
    discoveryYear: 1974,
    summary: "Named in honor of Glenn T. Seaborg, the first time an element was named for a living person.",
    shellConfig: "[Rn] 5f¹⁴ 6d⁴ 7s²"
  },
  {
    number: 107,
    symbol: "Bh",
    name: "Bohrium",
    mass: 270,
    category: "transition-metal",
    shells: [2, 8, 18, 32, 32, 13, 2],
    period: 7,
    group: 7,
    meltingPoint: null,
    boilingPoint: null,
    density: 37.1,
    electronegativity: null,
    stateAtSTP: "solid",
    discoverer: "GSI Darmstadt",
    discoveryYear: 1981,
    summary: "Named after Niels Bohr. Highly radioactive synthetic metal that decays rapidly.",
    shellConfig: "[Rn] 5f¹⁴ 6d⁵ 7s²"
  },
  {
    number: 108,
    symbol: "Hs",
    name: "Hassium",
    mass: 269,
    category: "transition-metal",
    shells: [2, 8, 18, 32, 32, 14, 2],
    period: 7,
    group: 8,
    meltingPoint: null,
    boilingPoint: null,
    density: 40.7,
    electronegativity: null,
    stateAtSTP: "solid",
    discoverer: "GSI Darmstadt",
    discoveryYear: 1984,
    summary: "Synthetic element named after the German state of Hesse. Highly unstable and radioactive.",
    shellConfig: "[Rn] 5f¹⁴ 6d⁶ 7s²"
  },
  {
    number: 109,
    symbol: "Mt",
    name: "Meitnerium",
    mass: 278,
    category: "transition-metal",
    shells: [2, 8, 18, 32, 32, 15, 2],
    period: 7,
    group: 9,
    meltingPoint: null,
    boilingPoint: null,
    density: 37.4,
    electronegativity: null,
    stateAtSTP: "solid",
    discoverer: "GSI Darmstadt",
    discoveryYear: 1982,
    summary: "Named to honor physicist Lise Meitner, co-discoverer of nuclear fission.",
    shellConfig: "[Rn] 5f¹⁴ 6d⁷ 7s²"
  },
  {
    number: 110,
    symbol: "Ds",
    name: "Darmstadtium",
    mass: 281,
    category: "transition-metal",
    shells: [2, 8, 18, 32, 32, 16, 2],
    period: 7,
    group: 10,
    meltingPoint: null,
    boilingPoint: null,
    density: 34.8,
    electronegativity: null,
    stateAtSTP: "solid",
    discoverer: "GSI Darmstadt",
    discoveryYear: 1994,
    summary: "Extremely radioactive synthetic element, decays through alpha emission in milliseconds.",
    shellConfig: "[Rn] 5f¹⁴ 6d⁸ 7s²"
  },
  {
    number: 111,
    symbol: "Rg",
    name: "Roentgenium",
    mass: 282,
    category: "transition-metal",
    shells: [2, 8, 18, 32, 32, 17, 2],
    period: 7,
    group: 11,
    meltingPoint: null,
    boilingPoint: null,
    density: 28.7,
    electronegativity: null,
    stateAtSTP: "solid",
    discoverer: "GSI Darmstadt",
    discoveryYear: 1994,
    summary: "Named after Wilhelm Röntgen, discoverer of X-rays. Extremely short-lived synthetic element.",
    shellConfig: "[Rn] 5f¹⁴ 6d⁹ 7s²"
  },
  {
    number: 112,
    symbol: "Cn",
    name: "Copernicium",
    mass: 285,
    category: "transition-metal",
    shells: [2, 8, 18, 32, 32, 18, 2],
    period: 7,
    group: 12,
    meltingPoint: 283,
    boilingPoint: 340,
    density: 23.7,
    electronegativity: null,
    stateAtSTP: "solid",
    discoverer: "GSI Darmstadt",
    discoveryYear: 1996,
    summary: "Named after Nicolaus Copernicus. Highly radioactive synthetic element, extremely volatile.",
    shellConfig: "[Rn] 5f¹⁴ 6d¹⁰ 7s²"
  },
  {
    number: 113,
    symbol: "Nh",
    name: "Nihonium",
    mass: 286,
    category: "post-transition-metal",
    shells: [2, 8, 18, 32, 32, 18, 3],
    period: 7,
    group: 13,
    meltingPoint: 700,
    boilingPoint: 1400,
    density: 16,
    electronegativity: null,
    stateAtSTP: "solid",
    discoverer: "RIKEN Team (Japan)",
    discoveryYear: 2004,
    summary: "The first chemical element discovered in an Asian country, named after Nihon (Japan).",
    shellConfig: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹"
  },
  {
    number: 114,
    symbol: "Fl",
    name: "Flerovium",
    mass: 289,
    category: "post-transition-metal",
    shells: [2, 8, 18, 32, 32, 18, 4],
    period: 7,
    group: 14,
    meltingPoint: 200,
    boilingPoint: 380,
    density: 14,
    electronegativity: null,
    stateAtSTP: "solid",
    discoverer: "Dubna Lab",
    discoveryYear: 1998,
    summary: "Named after the Flerov Laboratory where superheavy elements are synthesized.",
    shellConfig: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²"
  },
  {
    number: 115,
    symbol: "Mc",
    name: "Moscovium",
    mass: 290,
    category: "post-transition-metal",
    shells: [2, 8, 18, 32, 32, 18, 5],
    period: 7,
    group: 15,
    meltingPoint: 670,
    boilingPoint: 1400,
    density: 13.5,
    electronegativity: null,
    stateAtSTP: "solid",
    discoverer: "Dubna & Livermore Labs",
    discoveryYear: 2003,
    summary: "Extremely radioactive synthetic element, named after Moscow Oblast, Russia.",
    shellConfig: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³"
  },
  {
    number: 116,
    symbol: "Lv",
    name: "Livermorium",
    mass: 293,
    category: "post-transition-metal",
    shells: [2, 8, 18, 32, 32, 18, 6],
    period: 7,
    group: 16,
    meltingPoint: 700,
    boilingPoint: 1100,
    density: 12.9,
    electronegativity: null,
    stateAtSTP: "solid",
    discoverer: "Dubna & Livermore Labs",
    discoveryYear: 2000,
    summary: "Named to honor Lawrence Livermore National Laboratory and the city of Livermore, California.",
    shellConfig: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴"
  },
  {
    number: 117,
    symbol: "Ts",
    name: "Tennessine",
    mass: 294,
    category: "metalloid",
    shells: [2, 8, 18, 32, 32, 18, 7],
    period: 7,
    group: 17,
    meltingPoint: 650,
    boilingPoint: 880,
    density: 7.2,
    electronegativity: null,
    stateAtSTP: "solid",
    discoverer: "Dubna & Oak Ridge Labs",
    discoveryYear: 2010,
    summary: "Named after the state of Tennessee. Highly radioactive synthetic element.",
    shellConfig: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵"
  },
  {
    number: 118,
    symbol: "Og",
    name: "Oganesson",
    mass: 294,
    category: "noble-gas",
    shells: [2, 8, 18, 32, 32, 18, 8],
    period: 7,
    group: 18,
    meltingPoint: 325,
    boilingPoint: 350,
    density: 5.0,
    electronegativity: null,
    stateAtSTP: "solid",
    discoverer: "Dubna & Livermore Labs",
    discoveryYear: 2002,
    summary: "Named after Yuri Oganessian. Currently the highest atomic number and mass element on the table.",
    shellConfig: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶"
  }
];
